AWSTemplateFormatVersion: 2010-09-09
Description: My PHP Application
Transform: AWS::Serverless-2016-10-31
Resources:
  phpserver:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaLayerPHPTest
      Description: PHP Webserver
      CodeUri: src/php
      Runtime: provided
      Handler: index.main
      MemorySize: 128
      Timeout: 300
      Layers:
        - !Sub arn:aws:lambda:ap-northeast-1:${AWS::AccountId}:layer:php73:2
